# Generated by Django 3.0.2 on 2020-06-05 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bookissue', models.PositiveIntegerField(default=0)),
                ('bookreturn', models.PositiveIntegerField(default=0)),
                ('bookrenew', models.PositiveIntegerField(default=0)),
                ('deptname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.User')),
            ],
        ),
    ]
