# Generated by Django 3.0.2 on 2020-06-17 12:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorname', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('publisher', models.CharField(max_length=300)),
                ('isbn', models.CharField(default=0, max_length=100)),
                ('edition', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField(default=0)),
                ('copies', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(max_length=100)),
                ('ack', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('role', models.CharField(max_length=100)),
                ('usn', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.User')),
            ],
        ),
    ]
