# Generated by Django 3.0.2 on 2020-03-25 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='loginmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('contactnum', models.BigIntegerField()),
                ('email', models.EmailField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='visitorsmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students', models.CharField(max_length=5)),
                ('staff', models.CharField(max_length=5)),
                ('visitors', models.CharField(max_length=5)),
                ('username', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.loginmodel', to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='newbookmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorname', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('publisher', models.CharField(max_length=300)),
                ('isbn', models.CharField(max_length=100)),
                ('edition', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('copies', models.IntegerField(default=0)),
                ('username', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.loginmodel', to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='bookirmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bookissue', models.IntegerField(default=0)),
                ('bookreturn', models.IntegerField(default=0)),
                ('bookrenew', models.IntegerField(default=0)),
                ('deptname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.departments')),
                ('username', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.loginmodel', to_field='username')),
            ],
        ),
    ]
