# Generated by Django 3.0.2 on 2020-02-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='loginmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('contactnum', models.BigIntegerField()),
                ('email', models.EmailField(max_length=400)),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
