# Generated by Django 3.0.2 on 2020-04-24 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200421_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='newbookmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
