# Generated by Django 3.0.2 on 2020-04-24 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_newbookmodel_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newbookmodel',
        ),
    ]
