# Generated by Django 3.0.2 on 2020-03-22 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_visitors'),
    ]

    operations = [
        migrations.CreateModel(
            name='departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptname', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='visitors',
            new_name='visitorsmodel',
        ),
        migrations.CreateModel(
            name='bookirmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bookissue', models.IntegerField()),
                ('bookreturn', models.IntegerField()),
                ('bookrenew', models.IntegerField()),
                ('deptname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.departments')),
            ],
        ),
    ]
