# Generated by Django 3.0.2 on 2020-03-23 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200322_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookirmodel',
            old_name='usertype',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='visitorsmodel',
            old_name='usertype',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='departments',
            name='usertype',
        ),
        migrations.AlterField(
            model_name='bookirmodel',
            name='bookissue',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookirmodel',
            name='bookrenew',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookirmodel',
            name='bookreturn',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='newbookmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorname', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('publisher', models.CharField(max_length=300)),
                ('isbn', models.CharField(max_length=100)),
                ('edition', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('copies', models.IntegerField(default=0)),
                ('username', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.loginmodel')),
            ],
        ),
    ]
