# Generated by Django 3.0.2 on 2020-03-22 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_newbook'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='newbook',
            new_name='newbookmodel',
        ),
    ]
