# Generated by Django 3.0.2 on 2020-03-23 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200322_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departments',
            old_name='usertype',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='newbookmodel',
            old_name='usertype',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='visitorsmodel',
            old_name='usertype',
            new_name='username',
        ),
    ]
