# Generated by Django 3.0.2 on 2020-03-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200323_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookirmodel',
            name='bookissue',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookirmodel',
            name='bookrenew',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookirmodel',
            name='bookreturn',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='newbookmodel',
            name='copies',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='newbookmodel',
            name='edition',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='newbookmodel',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
