# Generated by Django 3.0.2 on 2020-03-23 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200323_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookirmodel',
            old_name='usertype',
            new_name='username',
        ),
    ]
