# Generated by Django 3.0.2 on 2020-03-23 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200323_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='username',
        ),
    ]
